#CREATE DATABASE Shopping_Behaviour;             #CREATING DATABASE
USE shopping_behaviour ;                         #USING DATABASE
-- select * from shopping_data;

-- QUES1 TOTAL REVENUE GENERATED BY MALE VS FEMALE ?
 SELECT 
 gender , SUM(purchase_amount) as revenue 
 from shopping_data 
 group by gender

-- QUES2 CUSTOMER USES DISCOUNT BUT STILL SPENT MORE THEN THE AVERAGE PURCHASE AMOUNT.
SELECT 
customer_id, purchase_amount 
FROM shopping_data 
WHERE discount_applied = 'YES' and purchase_amount >= (SELECT AVG(purchase_amount) 
FROM shopping_data)

-- QUES3 TOP5 PRODUCTS WITH HIGHEST REVIEW RATING.
SELECT 
item_purchased, 
AVG(review_rating) AS `AVERAGE PRODUCT RATING`
FROM shopping_data 
group by item_purchased 
order by AVG (review_rating) desc 
limit 5;

-- QUES4 COMPARE AVERAGE PURCHASE AMOUNT BETWEEN STANDARD AND EXPRESS SHIPPING.
SELECT 
shipping_type,
AVG(purchase_amount)
from shopping_data
WHERE shipping_type in ('standard','Express')
group by shipping_type

-- QUES5 SUBSCRIBED CUSTOMER SPEND MORE? COMPARING average spend and total revenue generated between subscribed and non-subscribed.
SELECT 
subscription_status,
COUNT(customer_id) as total_customer,
AVG (purchase_amount) as avg_spend ,
SUM(purchase_amount) as total_revenue 
from shopping_data
group by subscription_status
order by total_revenue, avg_spend desc;

-- QUES6 WHICH 5 PRODUCT WITH HIGHEST PURCHASES AND DISCOUNT APPLIED.
SELECT 
item_purchased,
(SUM(CASE WHEN discount_applied = 'YES' THEN 1 ELSE 0 END) / COUNT(*)) * 100 as discount_rate
from shopping_data
group by item_purchased
order by discount_rate DESC
limit 5;

-- QUES7 SEGMENTING CUSTOMER INTO NEW, RETURNING, LOYAL BASED ON THERE PREVIOUS NUMBER OF PURCHASES, AND SHOWING THE COUNT OF EACH SEGMENT.
WITH customer_type AS (
    SELECT 
        customer_id, 
        previous_purchases,
        CASE
            WHEN previous_purchases = 1 THEN 'NEW'
            WHEN previous_purchases >= 2 AND previous_purchases <= 10 THEN 'Returning'
            ELSE 'Loyal'
        END AS customer_segment
    FROM 
        shopping_data
)
SELECT 
    customer_segment, 
    COUNT(customer_id) AS `Number of customers` -- Use COUNT(customer_id) instead of COUNT(*)
FROM 
    customer_type
GROUP BY 
    customer_segment;

-- QUES8 customers who are repeat buyer and likely to subscribe.
select 
subscription_status,
count(customer_id) as repeat_buyers
from shopping_data
WHERE previous_purchases > 5
group by subscription_status

-- QUES9 REVENUE CONTRIBUTION OF EACH GROUP AGE.
SELECT 
age_group,
SUM(purchase_amount) as total_revenue 
from shopping_data
group by age_group
order by total_revenue desc;
